### ISSUE TITLE
Some inputs (by query log from Mathematicator database):

### ISSUE THREAD

**Issue by janbarasek** [mathematicator-core/numbers#9]
Some inputs (by query log from Mathematicator database):

- `45`
- `10.000`
- `4.`
- `3.0`
- `25....`

All these inputs must be converted to an integer, because the integer is the canonical form.

_Originally posted by @janbarasek in https://github.com/mathematicator-core/numbers/pull/8_

**Comment by flokixdev** [comment]
All these inputs are tested and valid at this time.
45 => 45
10.000 => 10.000
4. => 4
3.0 => 3.0
25.... => 25

The only exceptions from your intended behavior is that:
3.0 returns after casting to string 3.0
and 10.000 returns after casting 10.000

You can call on both ->toInteger() to solve the issue.

I think that behavior should be as is, because number 3.0 is not the same as 3. 3.0 represents number with another precision than 3. You will not lose the information in that case.

**Comment by janbarasek** [comment]
OK thank you. I think it can stay that way.

In the past, I converted the number `10.000` to an integer because there was rounding in the calculations, which must remain absolutely accurate.
